In [1]:
from selenium import webdriver as wd
import pandas as pd

In [2]:
driver = wd.Chrome('C:/Users/sxxhn/Desktop/lotte/chromedriver.exe')

In [3]:
import time
for n in range(2):
    target_site = 'http://www.giantsclub.com/html/?pcode=293'
    driver.get(target_site)
    time.sleep(5)

In [4]:
YEARS = [ option.get_attribute('value')
 for option in driver.find_elements_by_css_selector('#year_b > option')
    if option.get_attribute('value') 
]
YEARS[:2]

['2020', '2019']

In [6]:
data = list()
for year in YEARS[0:6]:
    year_sel = driver.find_element_by_id('year_b')
    year_sel.send_keys( year )
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="cont_wrapper"]/div/div[6]/div/form/input').click()
    time.sleep(5)
    
    # 데이터
    
    results = list()
    for td in driver.find_elements_by_css_selector('#tbl-rank2 > tbody > tr') :
        results.append(td.text.split())
        
    for i in range(0, len(results)) :
        data.append({
            '연도' : year,
            '홈원정' : results[i][0],
            '경기수' : results[i][1],
            '타수' : results[i][2],
            '안타' : results[i][3],
            '2루타' : results[i][4],
            '3루타' : results[i][5],
            '홈런' : results[i][6],
            '타점' : results[i][7],
            '볼넷' : results[i][8],
            '사구' : results[i][9],
            '삼진' : results[i][10],
            '득점' : results[i][11]
        })

In [7]:
df = pd.DataFrame(data)
df

      연도 홈원정 경기수    타수   안타  2루타 3루타   홈런   타점   볼넷  사구   삼진   득점
0   2020  원정  32  1153  308   47   0   29  140  112  16  201  150
1   2020   홈  29   984  280   65   2   23  147  100  10  178  155
2   2019  원정  70  2513  631   99  14   44  277  221  32  541  291
3   2019   홈  71  2406  600  115   8   46  268  208  33  544  287
4   2018  원정  72  2617  750  143   6  106  397  241  42  603  418
5   2018   홈  72  2513  734  146  11   97  395  230  39  554  403
6   2017  원정  72  2500  662  118   5   64  294  221  50  525  312
7   2017   홈  72  2475  761  132  12   86  399  232  59  485  426
8   2016  원정  72  2568  731  121  13   61  363  293  37  524  383
9   2016   홈  72  2452  712  132   7   66  371  303  46  540  397
10  2015  원정  72  2489  680  113   9   70  305  264  35  575  324
11  2015   홈  72  2431  700  139   9  103  410  264  33  590  435

In [ ]:
# 닫기 (창닫고, 프로세스도 종료)
driver.close()
driver.quit()