In [105]:
from selenium import webdriver as wd
import pandas as pd
import time

In [106]:
driver = wd.Chrome('C:/Users/sxxhn/Desktop/lotte/chromedriver.exe')

In [107]:
for n in range(2):
    target_site = 'https://www.koreabaseball.com/Record/Player/HitterBasic/Basic1.aspx'
    driver.get(target_site)
    time.sleep(5)

In [108]:
YEARS = [ option.get_attribute('value')
 for option in driver.find_elements_by_css_selector('#cphContents_cphContents_cphContents_ddlSeason_ddlSeason > option')
    if option.get_attribute('value') 
]
YEARS[-7:-1]

['2015', '2016', '2017', '2018', '2019', '2020']

In [115]:
data = list()
for year in YEARS[-7:-1]:
    # 연도 선택 
    year_sel = driver.find_element_by_id('cphContents_cphContents_cphContents_ddlSeason_ddlSeason')
    year_sel.send_keys( year )
    time.sleep(3)
    
    
    #팀 선택
    for j in range( 2, 12 ):
        driver.find_element_by_css_selector('#cphContents_cphContents_cphContents_ddlTeam_ddlTeam > option:nth-child('+str(j)+')').click()
        time.sleep(3)

        results = list()
        for i in range(1,31):
            for td in driver.find_elements_by_css_selector('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody > tr:nth-child('+str(i)+')'):
                results.append(td.text.split())

        for cnt in range(0, len(results)) :
            data.append({
                '연도' : year,
                '선수이름' : results[cnt][1],
                '팀명' : results[cnt][2],
                '타율' : results[cnt][3],
                '경기' : results[cnt][4],
                '타석' : results[cnt][5],
                '타수' : results[cnt][6],
                '득점' : results[cnt][7],
                '안타' : results[cnt][8],
                '2루타' : results[cnt][9],
                '3루타' : results[cnt][10],
                '홈런' : results[cnt][11],
                '루타' : results[cnt][12],
                '타점' : results[cnt][13],
                '희생번트' : results[cnt][14],
                '희생플라이' : results[cnt][15]
            })

In [117]:
# 데이터 하위값 확인
data[-10:]

[{'연도': '2020',
  '선수이름': '윤석민',
  '팀명': 'SK',
  '타율': '0.169',
  '경기': '27',
  '타석': '62',
  '타수': '59',
  '득점': '2',
  '안타': '10',
  '2루타': '1',
  '3루타': '0',
  '홈런': '1',
  '루타': '14',
  '타점': '8',
  '희생번트': '0',
  '희생플라이': '1'},
 {'연도': '2020',
  '선수이름': '정현',
  '팀명': 'SK',
  '타율': '0.165',
  '경기': '56',
  '타석': '103',
  '타수': '91',
  '득점': '10',
  '안타': '15',
  '2루타': '3',
  '3루타': '0',
  '홈런': '1',
  '루타': '21',
  '타점': '2',
  '희생번트': '3',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '유서준',
  '팀명': 'SK',
  '타율': '0.143',
  '경기': '5',
  '타석': '7',
  '타수': '7',
  '득점': '3',
  '안타': '1',
  '2루타': '1',
  '3루타': '0',
  '홈런': '0',
  '루타': '2',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '이재원',
  '팀명': 'SK',
  '타율': '0.111',
  '경기': '14',
  '타석': '47',
  '타수': '45',
  '득점': '1',
  '안타': '5',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '5',
  '타점': '2',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '김재현',
  '팀명': 'SK',
  '타율': '0.000',
  '경기': '3',
  '타석': '4',
  '타수': '4',
  '득점': '1',
  '안타': '0',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '0',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '김정빈',
  '팀명': 'SK',
  '타율': '-',
  '경기': '1',
  '타석': '0',
  '타수': '0',
  '득점': '0',
  '안타': '0',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '0',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '박민호',
  '팀명': 'SK',
  '타율': '-',
  '경기': '2',
  '타석': '0',
  '타수': '0',
  '득점': '0',
  '안타': '0',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '0',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '서진용',
  '팀명': 'SK',
  '타율': '-',
  '경기': '2',
  '타석': '0',
  '타수': '0',
  '득점': '0',
  '안타': '0',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '0',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '조영우',
  '팀명': 'SK',
  '타율': '-',
  '경기': '1',
  '타석': '0',
  '타수': '0',
  '득점': '0',
  '안타': '0',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '0',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'},
 {'연도': '2020',
  '선수이름': '하재훈',
  '팀명': 'SK',
  '타율': '-',
  '경기': '1',
  '타석': '0',
  '타수': '0',
  '득점': '0',
  '안타': '0',
  '2루타': '0',
  '3루타': '0',
  '홈런': '0',
  '루타': '0',
  '타점': '0',
  '희생번트': '0',
  '희생플라이': '0'}]

In [118]:
# 데이터프레임 생성
df = pd.DataFrame(data)
df

,연도,선수이름,팀명,타율,경기,타석,타수,득점,안타,2루타,3루타,홈런,루타,타점,희생번트,희생플라이
0,2015,유한준,넥센,0.362,139,598,520,103,188,42,1,23,301,116,1,8
1,2015,박병호,넥센,0.343,140,622,528,129,181,35,1,53,377,146,0,4
2,2015,허정협,넥센,0.333,4,6,6,1,2,0,0,0,2,0,0,0
3,2015,홍성갑,넥센,0.333,7,10,9,0,3,0,0,0,3,2,0,0
4,2015,이택근,넥센,0.326,105,401,347,61,113,16,1,10,161,44,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1760,2020,김정빈,SK,-,1,0,0,0,0,0,0,0,0,0,0,0
1761,2020,박민호,SK,-,2,0,0,0,0,0,0,0,0,0,0,0
1762,2020,서진용,SK,-,2,0,0,0,0,0,0,0,0,0,0,0
1763,2020,조영우,SK,-,1,0,0,0,0,0,0,0,0,0,0,0
1764,2020,하재훈,SK,-,1,0,0,0,0,0,0,0,0,0,0,0

In [119]:
# 닫기 (창닫고, 프로세스도 종료)
driver.close()
driver.quit()